version: '3'
services:

#  web-client:
#    container_name: "coinsurf-web-client"
#    build:
#      context: ../web-client
#    environment:
#      REACT_APP_WEB_SERVER_HOST: ${WEB_SERVER_HOST}
#      REACT_APP_WEB_SERVER_PORT: ${WEB_SERVER_PORT}
#      REACT_APP_WALLET_SERVER_HOST: ${WALLET_SERVER_HOST}
#      REACT_APP_WALLET_SERVER_PORT: ${WALLET_SERVER_PORT}
#      REACT_APP_WEB_CLIENT_PORT: ${WEB_CLIENT_PORT}
#      REACT_APP_PLUTUS_API_BASE: ${PLUTUS_API_BASE}
#      REACT_APP_CRYPTO_MANAGER_API_BASE: ${CRYPTO_MANAGER_API_BASE}
#    ports:
#      - "${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}"
#    stdin_open: true
#    depends_on:
#      - web-server

  web-server:
    container_name: "web-server"
    build:
      dockerfile: Dockerfile.local
      context: ./web-server
    volumes:
      - ./web-server:/app
    environment:
      APP_ENV: local
      WEB_SERVER_HOST: ${WEB_SERVER_HOST}
      WEB_SERVER_PORT: ${WEB_SERVER_PORT}
      WEB_CLIENT_HOST: ${WEB_CLIENT_HOST}
      WEB_CLIENT_PORT: ${WEB_CLIENT_PORT}
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
